# Generated by Django 6.0.5 on 2026-06-10 23:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_orderevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, choices=[('RECEIVED', 'Received'), ('PENDING_ANALYSIS', 'Pending Analysis'), ('QUOTED', 'Quoted'), ('APPROVED', 'Approved'), ('PENDING_DEPOSIT', 'Pending Deposit'), ('DEPOSIT_PAID', 'Deposit Paid'), ('PRINTING', 'Printing'), ('POST_PROCESSING', 'Post Processing'), ('READY', 'Ready'), ('PENDING_BALANCE', 'Pending Balance'), ('FULLY_PAID', 'Fully Paid'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], max_length=50, null=True)),
                ('new_status', models.CharField(choices=[('RECEIVED', 'Received'), ('PENDING_ANALYSIS', 'Pending Analysis'), ('QUOTED', 'Quoted'), ('APPROVED', 'Approved'), ('PENDING_DEPOSIT', 'Pending Deposit'), ('DEPOSIT_PAID', 'Deposit Paid'), ('PRINTING', 'Printing'), ('POST_PROCESSING', 'Post Processing'), ('READY', 'Ready'), ('PENDING_BALANCE', 'Pending Balance'), ('FULLY_PAID', 'Fully Paid'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='production_history_changes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='production_history', to='orders.order')),
            ],
            options={
                'db_table': 'production_history',
                'indexes': [models.Index(fields=['order'], name='production__order_i_f66e45_idx'), models.Index(fields=['changed_at'], name='production__changed_7b74eb_idx'), models.Index(fields=['new_status'], name='production__new_sta_4ffae5_idx'), models.Index(fields=['order', 'changed_at'], name='production__order_i_139893_idx')],
            },
        ),
    ]
