# Generated by Django 5.1.4 on 2026-06-10 23:06

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("weight_grams", models.DecimalField(decimal_places=2, max_digits=10)),
                ("print_time_hours", models.DecimalField(decimal_places=2, max_digits=10)),
                ("material_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("energy_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("labor_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("post_processing_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("packaging_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("risk_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("shipping_cost", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                ("profit_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("discount_amount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "quote_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="created_quotes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, related_name="quotes", to="orders.order"
                    ),
                ),
            ],
            options={
                "db_table": "quotes",
            },
        ),
        migrations.CreateModel(
            name="QuoteSnapshot",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("material_cost_per_kg", models.DecimalField(decimal_places=2, max_digits=10)),
                ("energy_cost_per_hour", models.DecimalField(decimal_places=2, max_digits=10)),
                ("labor_cost_per_hour", models.DecimalField(decimal_places=2, max_digits=10)),
                ("post_processing_cost_per_gram", models.DecimalField(decimal_places=2, max_digits=10)),
                ("packaging_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("failure_percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                ("profit_margin_percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                ("urgent_multiplier", models.DecimalField(decimal_places=2, max_digits=5)),
                ("express_multiplier", models.DecimalField(decimal_places=2, max_digits=5)),
                ("full_payment_discount_percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "quote",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT, related_name="snapshot", to="quotes.quote"
                    ),
                ),
            ],
            options={
                "db_table": "quote_snapshots",
            },
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(fields=["order"], name="quotes_order_i_ed45eb_idx"),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(fields=["quote_status"], name="quotes_quote_s_8f27d7_idx"),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(fields=["created_at"], name="quotes_created_c74d71_idx"),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(fields=["expires_at"], name="quotes_expires_15781a_idx"),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(fields=["order", "quote_status"], name="quotes_order_i_37af8c_idx"),
        ),
    ]
