# Generated by Django 5.1.4 on 2026-06-20 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_add_printer_fk_update_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quotesnapshot',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=16, max_digits=5),
        ),
    ]
