# Generated by Django 5.1.4 on 2026-06-10 23:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_type', models.CharField(choices=[('IMAGE', 'Image'), ('STL', 'STL'), ('OBJ', 'OBJ'), ('THREE_MF', '3MF'), ('PAYMENT_PROOF', 'Payment Proof')], max_length=30)),
                ('file_url', models.TextField()),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size_bytes', models.PositiveBigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'request_files',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('REFERENCE', 'Reference'), ('PRINTABLE_FILE', 'Printable File')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('color', models.CharField(blank=True, default='', max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('dimensions_notes', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENT', 'Urgent'), ('EXPRESS', 'Express')], default='NORMAL', max_length=20)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PENDING_ANALYSIS', 'Pending Analysis'), ('QUOTED', 'Quoted'), ('APPROVED', 'Approved'), ('PENDING_DEPOSIT', 'Pending Deposit'), ('DEPOSIT_PAID', 'Deposit Paid'), ('PRINTING', 'Printing'), ('POST_PROCESSING', 'Post Processing'), ('READY', 'Ready'), ('PENDING_BALANCE', 'Pending Balance'), ('FULLY_PAID', 'Fully Paid'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], max_length=50)),
                ('payment_status', models.CharField(choices=[('NO_PAYMENT', 'No Payment'), ('DEPOSIT_PENDING', 'Deposit Pending'), ('DEPOSIT_PAID', 'Deposit Paid'), ('BALANCE_PENDING', 'Balance Pending'), ('FULLY_PAID', 'Fully Paid'), ('REFUNDED', 'Refunded')], default='NO_PAYMENT', max_length=50)),
                ('delivery_method', models.CharField(choices=[('PICKUP', 'Pickup'), ('SHIPPING', 'Shipping')], default='PICKUP', max_length=20)),
                ('estimated_delivery_date', models.DateField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('ai_analysis', models.JSONField(blank=True, null=True)),
                ('ai_notes', models.TextField(blank=True, default='')),
                ('ai_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ai_category', models.CharField(blank=True, default='', max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
