# Generated by Django 6.0.5 on 2026-06-10 23:27

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("ORDER_CREATED", "Order Created"),
                            ("FILE_UPLOADED", "File Uploaded"),
                            ("QUOTE_CREATED", "Quote Created"),
                            ("QUOTE_ACCEPTED", "Quote Accepted"),
                            ("QUOTE_REJECTED", "Quote Rejected"),
                            ("PAYMENT_PROOF_UPLOADED", "Payment Proof Uploaded"),
                            ("PAYMENT_CONFIRMED", "Payment Confirmed"),
                            ("PAYMENT_REJECTED", "Payment Rejected"),
                            ("DEPOSIT_CONFIRMED", "Deposit Confirmed"),
                            ("BALANCE_CONFIRMED", "Balance Confirmed"),
                            ("FULL_PAYMENT_CONFIRMED", "Full Payment Confirmed"),
                            ("STATUS_CHANGED", "Status Changed"),
                            ("PRIORITY_CHANGED", "Priority Changed"),
                            ("SHIPPING_ADDRESS_UPDATED", "Shipping Address Updated"),
                            ("SHIPMENT_CREATED", "Shipment Created"),
                            ("ORDER_DELIVERED", "Order Delivered"),
                            ("REFUND_REQUESTED", "Refund Requested"),
                            ("REFUND_PROCESSED", "Refund Processed"),
                            ("ORDER_CANCELLED", "Order Cancelled"),
                        ],
                        max_length=100,
                    ),
                ),
                ("event_description", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, related_name="events", to="orders.order"
                    ),
                ),
            ],
            options={
                "db_table": "order_events",
                "indexes": [
                    models.Index(fields=["order"], name="order_event_order_i_f3f7d4_idx"),
                    models.Index(fields=["event_type"], name="order_event_event_t_e54baa_idx"),
                    models.Index(fields=["created_at"], name="order_event_created_6ce890_idx"),
                    models.Index(fields=["order", "created_at"], name="order_event_order_i_56d331_idx"),
                ],
            },
        ),
    ]
