# Generated by Django 5.1.4 on 2026-06-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('PENDING_ANALYSIS', 'Pending Analysis'), ('QUOTED', 'Quoted'), ('APPROVED', 'Approved'), ('PENDING_DEPOSIT', 'Pending Deposit'), ('DEPOSIT_PAID', 'Deposit Paid'), ('PRINTING', 'Printing'), ('POST_PROCESSING', 'Post Processing'), ('READY', 'Ready'), ('PENDING_BALANCE', 'Pending Balance'), ('FULLY_PAID', 'Fully Paid'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='RECEIVED', max_length=50),
        ),
    ]
