# Generated by Django 5.1.4 on 2026-06-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_internalnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderevent',
            name='event_type',
            field=models.CharField(choices=[('ORDER_CREATED', 'Order Created'), ('FILE_UPLOADED', 'File Uploaded'), ('QUOTE_CREATED', 'Quote Created'), ('QUOTE_ACCEPTED', 'Quote Accepted'), ('QUOTE_REJECTED', 'Quote Rejected'), ('PAYMENT_PROOF_UPLOADED', 'Payment Proof Uploaded'), ('PAYMENT_CONFIRMED', 'Payment Confirmed'), ('PAYMENT_REJECTED', 'Payment Rejected'), ('DEPOSIT_CONFIRMED', 'Deposit Confirmed'), ('BALANCE_CONFIRMED', 'Balance Confirmed'), ('FULL_PAYMENT_CONFIRMED', 'Full Payment Confirmed'), ('STATUS_CHANGED', 'Status Changed'), ('PRIORITY_CHANGED', 'Priority Changed'), ('SHIPPING_ADDRESS_UPDATED', 'Shipping Address Updated'), ('SHIPMENT_CREATED', 'Shipment Created'), ('ORDER_DELIVERED', 'Order Delivered'), ('REFUND_REQUESTED', 'Refund Requested'), ('REFUND_PROCESSED', 'Refund Processed'), ('ORDER_CANCELLED', 'Order Cancelled'), ('DEPOSIT_REMINDER', 'Deposit Reminder')], max_length=100),
        ),
    ]
