# Generated by Django 5.1.4 on 2026-06-20 01:18

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('material_type', models.CharField(choices=[('PLA', 'PLA'), ('PETG', 'PETG'), ('ABS', 'ABS'), ('TPU', 'TPU'), ('RESIN', 'Resina'), ('OTHER', 'Otro')], max_length=20)),
                ('brand', models.CharField(blank=True, default='', max_length=100)),
                ('available_colors', models.JSONField(default=list)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_grams', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_stock_grams', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'materials',
                'ordering': ['material_type', 'name'],
                'indexes': [models.Index(fields=['material_type'], name='materials_materia_728bd0_idx'), models.Index(fields=['is_active'], name='materials_is_acti_c341ca_idx')],
            },
        ),
    ]
