# Generated by Django 5.1.4 on 2026-06-08 04:40

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusinessConfig",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("material_cost_per_kg", models.DecimalField(decimal_places=2, max_digits=10)),
                ("energy_cost_per_hour", models.DecimalField(decimal_places=2, max_digits=10)),
                ("labor_cost_per_hour", models.DecimalField(decimal_places=2, max_digits=10)),
                ("post_processing_cost_per_gram", models.DecimalField(decimal_places=2, max_digits=10)),
                ("packaging_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("failure_percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                ("profit_margin_percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                ("urgent_multiplier", models.DecimalField(decimal_places=2, max_digits=5)),
                ("express_multiplier", models.DecimalField(decimal_places=2, max_digits=5)),
                ("full_payment_discount_percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                ("deposit_deadline_hours", models.PositiveIntegerField()),
                ("balance_deadline_days", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "business_config",
            },
        ),
        migrations.CreateModel(
            name="BusinessHours",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("weekday", models.PositiveSmallIntegerField()),
                ("is_open", models.BooleanField(default=True)),
                ("opening_time", models.TimeField(blank=True, null=True)),
                ("closing_time", models.TimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "business_hours",
                "ordering": ["weekday"],
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("holiday_date", models.DateField(unique=True)),
                ("holiday_name", models.CharField(max_length=255)),
                ("affects_shipping", models.BooleanField(default=True)),
                ("affects_pickup", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "holidays",
                "ordering": ["holiday_date"],
            },
        ),
        migrations.CreateModel(
            name="PaymentInstructions",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("bank_name", models.CharField(max_length=100)),
                ("account_holder", models.CharField(max_length=255)),
                ("account_number", models.CharField(blank=True, default="", max_length=50)),
                ("clabe", models.CharField(blank=True, default="", max_length=30)),
                ("card_number", models.CharField(blank=True, default="", max_length=30)),
                ("additional_notes", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "payment_instructions",
            },
        ),
    ]
