# Generated by Django 5.1.4 on 2026-06-16 06:17

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configuration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Printer",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150)),
                ("brand", models.CharField(blank=True, default="", max_length=100)),
                ("power_watts", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "printers",
                "ordering": ["brand", "name"],
            },
        ),
        migrations.RemoveField(
            model_name="businessconfig",
            name="energy_cost_per_hour",
        ),
        migrations.AddField(
            model_name="businessconfig",
            name="electricity_rate_kwh",
            field=models.DecimalField(decimal_places=4, default="2.0000", max_digits=10),
        ),
    ]
