# Generated by Django 5.1.4 on 2026-06-20 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_add_printer_max_power_watts'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessconfig',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=16, max_digits=5),
        ),
    ]
