# Generated by Django 5.1.4 on 2026-06-10 23:04

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("carrier_name", models.CharField(blank=True, default="", max_length=100)),
                ("tracking_number", models.CharField(blank=True, default="", max_length=100)),
                ("shipping_cost", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("shipped_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("shipping_notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT, related_name="shipment", to="orders.order"
                    ),
                ),
            ],
            options={
                "db_table": "shipments",
                "indexes": [
                    models.Index(fields=["tracking_number"], name="shipments_trackin_cc256d_idx"),
                    models.Index(fields=["shipped_at"], name="shipments_shipped_2b43b0_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ShippingAddress",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("address_name", models.CharField(max_length=100)),
                ("street", models.CharField(max_length=255)),
                ("external_number", models.CharField(max_length=50)),
                ("internal_number", models.CharField(blank=True, default="", max_length=50)),
                ("neighborhood", models.CharField(max_length=255)),
                ("postal_code", models.CharField(max_length=20)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("country", models.CharField(default="Mexico", max_length=100)),
                ("references", models.TextField(blank=True, default="")),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="shipping_addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "shipping_addresses",
                "indexes": [
                    models.Index(fields=["user"], name="shipping_ad_user_id_d79e82_idx"),
                    models.Index(fields=["postal_code"], name="shipping_ad_postal__53cc42_idx"),
                    models.Index(fields=["city"], name="shipping_ad_city_7e40ba_idx"),
                    models.Index(fields=["state"], name="shipping_ad_state_4ac6ef_idx"),
                ],
            },
        ),
    ]
