# Generated by Django 6.0.5 on 2026-06-10 23:29

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0003_orderevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("DEPOSIT", "Deposit"),
                            ("BALANCE", "Balance"),
                            ("FULL_PAYMENT", "Full Payment"),
                            ("REFUND", "Refund"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(choices=[("BANK_TRANSFER", "Bank Transfer"), ("CASH", "Cash")], max_length=30),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("CONFIRMED", "Confirmed"), ("REJECTED", "Rejected")],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                ("proof_file_url", models.TextField(blank=True, default="")),
                ("manual_confirmation", models.BooleanField(default=False)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, related_name="payments", to="orders.order"
                    ),
                ),
            ],
            options={
                "db_table": "payments",
                "indexes": [
                    models.Index(fields=["order"], name="payments_order_i_b32b33_idx"),
                    models.Index(fields=["payment_type"], name="payments_payment_ba7b87_idx"),
                    models.Index(fields=["payment_method"], name="payments_payment_ee488d_idx"),
                    models.Index(fields=["payment_status"], name="payments_payment_bbdde9_idx"),
                    models.Index(fields=["created_at"], name="payments_created_e3a130_idx"),
                    models.Index(fields=["confirmed_at"], name="payments_confirm_e8052e_idx"),
                    models.Index(fields=["order", "payment_status"], name="payments_order_i_f2ff76_idx"),
                ],
            },
        ),
    ]
